// This file was generated by silverstripe/tx-translator from client/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "ShareDraftContent.DESCRIPTION": "Anyone with this link can view the draft version of this page.",
    "ShareDraftContent.FETCH_ERROR": "There was a problem generating the shareable link!",
    "ShareDraftContent.LEARN_MORE": "Learn more",
    "ShareDraftContent.LINK_HELP": "Link to share draft content",
    "ShareDraftContent.LOADING": "Loading...",
    "ShareDraftContent.SHARE": "Share",
    "ShareDraftContent.SHARE_DRAFT_CONTENT": "Share draft content"
});
}