// This file was generated by silverstripe/tx-translator from client/lang/src/eo.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "ShareDraftContent.LOADING": "Ŝargas...",
    "ShareDraftContent.FETCH_ERROR": "Okazis problemo generi la komunan ligilon!",
    "ShareDraftContent.DESCRIPTION": "Kiu havas ĉi tiun ligilon, tiu povas vidi la malnetan version de ĉi tiu paĝo.",
    "ShareDraftContent.LEARN_MORE": "Lerni plu",
    "ShareDraftContent.LINK_HELP": "Ligi por kunhavi malnetan enhavon",
    "ShareDraftContent.SHARE": "Kunhavigi",
    "ShareDraftContent.SHARE_DRAFT_CONTENT": "Kunhavigi malnetan enhavon"
});
}