// This file was generated by silverstripe/tx-translator from client/lang/src/sk.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "ShareDraftContent.DESCRIPTION": "Ktokoľvek s týmto odkazom si môže zobraziť koncept tejto stránky.",
    "ShareDraftContent.FETCH_ERROR": "Pri generovaní odkazu na zdieľanie sa vyskytol problém!",
    "ShareDraftContent.LEARN_MORE": "Zistiť viac",
    "ShareDraftContent.LINK_HELP": "Odkaz na zdieľanie konceptu obsahu",
    "ShareDraftContent.LOADING": "Načítava sa...",
    "ShareDraftContent.SHARE": "Zdielať",
    "ShareDraftContent.SHARE_DRAFT_CONTENT": "Zdielať koncept obsahu"
});
}