// This file was generated by silverstripe/tx-translator from client/lang/src/sl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "ShareDraftContent.LOADING": "Nalagam ...",
    "ShareDraftContent.FETCH_ERROR": "Pri generiranju povezave je prišlo do napake.",
    "ShareDraftContent.DESCRIPTION": "Vsak, ki ima to povezavo, lahko dostopa do osnutka te strani.",
    "ShareDraftContent.LEARN_MORE": "Več o tem",
    "ShareDraftContent.LINK_HELP": "Povezava do osnutka strani",
    "ShareDraftContent.SHARE": "Posreduj",
    "ShareDraftContent.SHARE_DRAFT_CONTENT": "Posredujte osnutek strani"
});
}