// This file was generated by silverstripe/tx-translator from client/lang/src/sv.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "ShareDraftContent.LOADING": "Laddar...",
    "ShareDraftContent.FETCH_ERROR": "Det gick inte att generera den delbara länken!",
    "ShareDraftContent.DESCRIPTION": "Alla med den här länken kan se utkastversionen av den här sidan.",
    "ShareDraftContent.LEARN_MORE": "Lär dig mer",
    "ShareDraftContent.LINK_HELP": "Länk för att dela utkast innehåll",
    "ShareDraftContent.SHARE": "Dela",
    "ShareDraftContent.SHARE_DRAFT_CONTENT": "Dela innehåll i utkast"
});
}