---
Name: sharedraftcontent
After: framework/routes#coreroutes
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\ShareDraftContent\Extensions\ShareDraftContentSiteTreeExtension
SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - SilverStripe\ShareDraftContent\Extensions\ShareDraftContentRequirementsExtension
SilverStripe\Control\Controller:
  extensions:
    - SilverStripe\ShareDraftContent\Extensions\ShareDraftContentControllerExtension
SilverStripe\Assets\Shortcodes\FileShortcodeProvider:
  extensions:
    - SilverStripe\ShareDraftContent\Extensions\ShareDraftContentFileShortcodeProviderExtension
SilverStripe\Control\Director:
  rules:
    'preview': 'SilverStripe\ShareDraftContent\Controllers\ShareDraftController'
